image: docker:dind

variables:
  PIPELINE_SERVICE_NAME: serverless_service
  PIPELINE_NODEJS_IMAGE_INTERMEDIATE: ${CI_REGISTRY}/${CI_PROJECT_PATH}/nodejs:ci-${CI_PIPELINE_ID}
  PIPELINE_NODEJS_IMAGE_FINAL: ${CI_REGISTRY}/${CI_PROJECT_PATH}/nodejs:final-${CI_PIPELINE_ID}
  APP_ENV_STAGING: STAGING
  APP_ENV_PRODUCTION: PROD
  APP_NAME: serverless-service
  AWS_REGION: eu-west-1

##### docker login with CI credentials #####
.login_docker_script: &login_docker
                        docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}

stages:
  - build
  - test
  - deploy_function
  - deploy_pages

build_nodejs:
  stage: build
  script:
    - *login_docker
    - echo "Building NODEJS '${PIPELINE_NODEJS_IMAGE_INTERMEDIATE}'"
    - docker build
      --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      --build-arg VCS_REF=${CI_COMMIT_SHA}
      -t ${PIPELINE_NODEJS_IMAGE_INTERMEDIATE} -f deploy/nodejs/Dockerfile .
    - echo "Pushing NODEJS '${PIPELINE_NODEJS_IMAGE_INTERMEDIATE}'"
    - docker push ${PIPELINE_NODEJS_IMAGE_INTERMEDIATE}
  except:
    - tags

test:
  stage: test
  image: ${PIPELINE_NODEJS_IMAGE_INTERMEDIATE}
  dependencies:
    - build_nodejs
  script:
    - npm install
    - npm test

production:
  stage: deploy_function
  image: ${PIPELINE_NODEJS_IMAGE_INTERMEDIATE}
  when: manual
  before_script:
    - FAILURE_MESSAGE="Must define \$AWS_ACCESS_KEY_ID and \$AWS_SECRET_ACCESS_KEY. Add keys to $CI_PROJECT_URL/-/settings/ci_cd"
    - test -z "$AWS_SECRET_ACCESS_KEY" && echo $FAILURE_MESSAGE && exit 1
    - test -z "$AWS_ACCESS_KEY_ID" && echo $FAILURE_MESSAGE && exit 1
  script:
    - npm install
    - npm run deploy -- --stage production --verbose
  environment: production
  only:
    - master
  artifacts:
    paths:
      - stack.json
    expire_in: 2 weeks

pages:
  stage: deploy_pages
  when: manual
  dependencies:
    - production
  script:
    - cp stack.json ./public/stack.json
  environment: production_pages
  only:
    - master
  artifacts:
    paths:
      - ./public/
